---
- name: Setup web server on Ubuntu
  hosts: app-server
  become: yes

  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker CE repository
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable'
        state: present

    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: present

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Copy SSH public key to remote server
      ansible.builtin.copy:
        src: /home/ubuntu/.ssh/id_ed25519.pub 
        dest: /root/.ssh/authorized_keys
        mode: '0600'

    - name: Clone app repo
      ansible.builtin.git:
        repo: 'https://github.com/OrHazizaNitzanimToTech/Or-CICD.git'
        dest: /opt/my-app

    - name: Build Docker image
      ansible.builtin.command:
        cmd: docker build -t orapp /opt/my-app

    - name: Commit changes to local Git repository
      ansible.builtin.command:
        cmd: git -C /opt/my-app add . && git -C /opt/my-app commit -m "Updated Docker image"  
    - name: Push changes to remote Git repository
      ansible.builtin.command:
        cmd: git -C /opt/my-app push origin master 

    - name: Start Docker app
      ansible.builtin.command:
        cmd: docker run -d -p 8080:80 orapp  
